# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Consortia
email: info@consortia.net
description: Consortia is a creative office in New York City. We develop new frameworks for communication.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: consortianet
facebook:
  publisher: https://www.facebook.com/consortianet/
logo: /assets/images/consortia-logo.png
social:
  links:
    - https://twitter.com/consortianet
    - https://are.na/consortia-systems
    - https://www.facebook.com/consortianet
    - https://www.instagram.com/consortianet

# Build settings
highlighter: rouge
markdown: kramdown
permalink: /:categories/:title.html
sass:
  sass_dir: _sass
include: ['_pages']
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
jekyll_get:
  - data: techno-animism
    json: 'http://api.are.na/v2/channels/techno-animism?per=10'
  - data: consortia office
    json: 'http://api.are.na/v2/channels/consortia-office'
  - data: hd
    json: 'http://api.are.na/v2/channels/hd?per=4'
